# Site settings
title: Sofia Cruz
email: sofiapontecruz@gmail.com
url: https://github.com/jeromelachaud/freelancer-theme
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
keywords: "your keywords, separated by commas"
skills: "Fashion Designer"
meta_author: Cruz Sofia

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: DDA0DD #DDA0DD
  secondary: ffffff #ffffff
  secondary-dark: 000000 #000000

# Footer settings
footer:
  copyright: Sofia Cruz
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/sofiapontecruz/
  - title: instagram
    url: https://www.instagram.com/yours.tobee/
  - title: envelope
    url: mailto:sofiapontecruz@gmail.com

# Postal address (add as many lines as necessary)
address:
  - line: Braga
  - line: Portugal
  - line: sofiapontecruz@gmail.com

# Credits content
credits:

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
